### ISSUE TITLE
Please add `IpStackStream::Icmp` 

### ISSUE THREAD

**Issue by xmh0511** [narrowlink/ipstack#1]
Currently, this library can forward `tcp`, and `udp`. However, sometimes we want to forward `icmp` packet to the remote, for example, have it a customized processed (i.e. not a simple forward). Please add `IpStackStream::Icmp` such that we can process the packet in the branch of `match ip_stack.accept().await.unwrap()`.

**Comment by SajjadPourali** [comment]
> Currently, this library can forward `tcp`, and `udp`. However, sometimes we want to forward `icmp` packet to the remote, for example, have it a customized processed (i.e. not a simple forward). Please add `IpStackStream::Icmp` such that we can process the packet in the branch of `match ip_stack.accept().await.unwrap()`.

For sure, There is a plan to add support for some messages in both ICMP4 and ICMP6.

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/ipstack/pull/17
