### ISSUE TITLE
we can re-consider supporting freebsd now

### ISSUE THREAD

**Issue by xmh0511** [narrowlink/ipstack#24]
Since these defined packet information structures prevent `ipstack` from supporting FreeBSD, which is caused by `tun`, however, `ipstack` can support FreeBSD together with `tun2` since `tun2` supports FreeBSD now, we can re-consider supporting the platform by reverting https://github.com/narrowlink/ipstack/commit/04b7ac7c8e1d9e533584c6f817fa24b63258299a.

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/ipstack/commit/b29ace0b16578d734459ae87b97e5b4e8ab68e19

**Comment by xmh0511** [comment]
FreeBSD always does not have packet information, in my test. see https://github.com/ssrlive/rust-tun/blob/v2/src/platform/freebsd/device.rs#L454
