### ISSUE TITLE
There always lots of `Invalid TCP packet`

### ISSUE THREAD

**Issue by ssrlive** [narrowlink/ipstack#26]
Here the screenshot. I don't know the reason.

![image](https://github.com/narrowlink/ipstack/assets/30760636/afdad24b-f94c-45e3-a0d4-3c65118f3ff2)

**Comment by SajjadPourali** [comment]
pcap file is required.

**Comment by ssrlive** [comment]
![image](https://github.com/narrowlink/ipstack/assets/30760636/1a893191-b06b-4f42-990f-a91074fdce2c)

[a.zip](https://github.com/narrowlink/ipstack/files/14626200/a.zip)

**Comment by ssrlive** [comment]
![image](https://github.com/narrowlink/ipstack/assets/30760636/3d380933-4875-4da4-a00d-e13284e7f2ba)


[b.zip](https://github.com/narrowlink/ipstack/files/14626289/b.zip)

**Comment by ssrlive** [comment]
[d.zip](https://github.com/narrowlink/ipstack/files/14626936/d.zip)

![image](https://github.com/narrowlink/ipstack/assets/30760636/eb0f1a6f-6950-47c2-98fa-a32074d52b11)

**Comment by SajjadPourali** [comment]
Thanks.
I've just identified the issue and am working on resolving it.

**Comment by SajjadPourali** [comment]
There is still a minor issue with finishing the connection, which I'll address in the future.
