### ISSUE TITLE
Seems still does not solve the problem on the Windows platform

### ISSUE THREAD

**Issue by xmh0511** [narrowlink/ipstack#31]
<img width="1219" alt="截屏2024-03-28 11 40 45" src="https://github.com/narrowlink/ipstack/assets/17973891/b1b846d4-d978-42c4-81d6-8d5081fbbfa8">

As seen in the picture, I used the latest one in the github, and the first problem in https://github.com/narrowlink/ipstack/issues/27  remains unchanged. 

https://github.com/narrowlink/ipstack/assets/17973891/e159d0b8-598d-4231-8c2c-5c0e87016794

**Comment by xmh0511** [comment]
It seems that https://github.com/narrowlink/ipstack/commit/437ef17fe7e0a31b02986ae7ab6c14b9169132d6 fix the issue, however, the subsequent commit re-introduces the issue.

**Comment by SajjadPourali** [comment]
> It seems that [437ef17](https://github.com/narrowlink/ipstack/commit/437ef17fe7e0a31b02986ae7ab6c14b9169132d6) fix the issue, however, the subsequent commit re-introduces the issue.

True, as I mentioned in the comment on https://github.com/narrowlink/ipstack/issues/27#issuecomment-2024318024, you need to manually shut down the stream yourself by calling `stream.shutdown().await`. I previously implemented auto shutdown when the stream dropped, but since Rust's drop does not support async, I used `task::block_in_place` that dramatically affects memory allocation and recursion. In other words, until finding a way to implement the drop asynchronously, you need to manually shutdown the stream yourself when a timeout reached.

**Comment by SajjadPourali** [comment]
Another solution is resetting the connection.

```rust
impl Drop for IpStackTcpStream {
    fn drop(&mut self) {
        if let Ok(p) = self.create_rev_packet(RST | ACK, TTL, None, Vec::new()) {
            _ = self.packet_sender.send(p);
        }
        if let Ok(p) = self.create_rev_packet(NON, DROP_TTL, None, Vec::new()) {
            _ = self.packet_sender.send(p);
        }
    }
}

```

<img width="1138" alt="Screenshot 2024-03-28 at 12 23 19 AM" src="https://github.com/narrowlink/ipstack/assets/20374762/0069f3a7-4874-48ea-9e0a-6083521325a8">

**Comment by xmh0511** [comment]
> Another solution is resetting the connection.
> 
> ```rust
> impl Drop for IpStackTcpStream {
>     fn drop(&mut self) {
>         if let Ok(p) = self.create_rev_packet(RST | ACK, TTL, None, Vec::new()) {
>             _ = self.packet_sender.send(p);
>         }
>         if let Ok(p) = self.create_rev_packet(NON, DROP_TTL, None, Vec::new()) {
>             _ = self.packet_sender.send(p);
>         }
>     }
> }
> ```
> 
> <img alt="Screenshot 2024-03-28 at 12 23 19 AM" width="1138" src="https://private-user-images.githubusercontent.com/20374762/317590029-0069f3a7-4874-48ea-9e0a-6083521325a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDI1MTksIm5iZiI6MTcxMTYwMjIxOSwicGF0aCI6Ii8yMDM3NDc2Mi8zMTc1OTAwMjktMDA2OWYzYTctNDg3NC00OGVhLTllMGEtNjA4MzUyMTMyNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA1MDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMDk3OWU5ZWJhN2Y1MTJmMmI5NjFjMjcwNGYxOGYyMjc1YTg3OWU0NGFjZGYxNjgxMGI1YTI0ZDk0NTEyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eAVDnvYjIQpuZehKJ5i44tPeS53C9puBsG6RWd9UxCY">

We could investigate how the standard library or tokio resolves this issue when dropping the instance.

**Comment by xmh0511** [comment]
@SajjadPourali 

Shall we wrapper the `IpstackTcpStream` in a Guard-like struct with the `Option<IpstackTcpStream>` field as its inner instance, and every time the drop of Guard-like struct is invoked, we take out the field and send it to a specific task that is used to `shutdown` the inner `IpstackTcpStream` through a channel? 

The `Guard-like` struct behaves like a `IpstackTcpStream`, that is, `read`, `write`, `flush`, and `shutdown` are proxy to its inner `IpstackTcpStream`.

**Comment by SajjadPourali** [comment]
> ###Update
> 
> The `tcpstream` in `tokio` shutdown the connection after dropping(i.e. it does not reset the connection).

True, because the operating system is responsible for managing the TCP/IP stack, and neither Tokio nor Rust has control over it.

**Comment by xmh0511** [comment]
`Ipstack` is that an "operating system", see this approach in https://github.com/narrowlink/ipstack/issues/31#issuecomment-2024430848, is it available?

**Comment by xmh0511** [comment]
<img width="1273" alt="截屏2024-03-28 13 43 35" src="https://github.com/narrowlink/ipstack/assets/17973891/f7356b0a-e7d0-4512-aee9-0a1dd6001cac">

It seems that the `shutdown` of `IpstackTcpStream` still has some issues.

**Comment by xmh0511** [comment]
https://github.com/narrowlink/ipstack/pull/32

**Comment by SajjadPourali** [comment]
https://github.com/narrowlink/ipstack/pull/33
