### ISSUE TITLE
The crate in crates.io should update its cargo.lock

### ISSUE THREAD

**Issue by xmh0511** [narrowlink/ipstack#50]
https://docs.rs/crate/ipstack/0.0.10/source/Cargo.lock

[[package]]
name = "etherparse"
version = "0.14.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "095ab548cf452be5813424558a18af88f0a620d0f4a3d8793aa09311a3b6fa5f"
dependencies = [
 "arrayvec",
]

The crate on `crates.io` is locked its dependency `etherparse`'s version to be `0.14.3`, which is not compatible with `0.15` written in https://github.com/narrowlink/ipstack/blob/main/Cargo.toml#L21

**Comment by SajjadPourali** [comment]
I don’t see the issues as the Etherparse version in the crate is 0.14.x.

**Comment by xmh0511** [comment]
> I don’t see the issues, could you please elaborate the issue?

with this dependencies
````
[dependencies]
tokio = { version = "1.37", features = [
    "sync",
    "rt",
    "time",
    "io-util",
    "macros",
	"rt-multi-thread",
] }

tun2 = { version = "2", features = ["async"] }
ipstack = "0.0.10"
etherparse = { version = "0.15", default-features = false, features = ["std"] }
socket2 = "0.5.7"
````
will get an error
```
error[E0308]: mismatched types
  --> src/main.rs:39:65
   |
39 | ..._ipv4() && u.ip_protocol() == etherparse::IpNumber(1) {
   |               ---------------    ^^^^^^^^^^^^^^^^^^^^^^^ expected `IpNumber`, found a different `IpNumber`
   |               |
   |               expected because this is `etherparse::net::ip_number_impl::IpNumber`
   |
   = note: `IpNumber` and `IpNumber` have similar names, but are actually distinct types

`IpNumber` is defined in crate `etherparse`
etherparse-0.15.0/src/net/ip_number_impl.rs:47:1

`IpNumber` is defined in crate `etherparse`
etherparse-0.14.3/src/net/ip_number_impl.rs:47:1

47 | pub struct IpNumber(pub u8);
   | ^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `etherparse` are being used?

```

This is a minimal reproduction project
[use.zip](https://github.com/user-attachments/files/16355853/use.zip)

**Comment by SajjadPourali** [comment]
The issue involves exposing the IP number through the API.

Thanks for the report
